export default {
  docket: 'İletişim',
  title: 'İletişim',
  intro: 'Randevu talebi ve genel sorular için aşağıdaki kanallar kullanılabilir.',
  formLabel: 'Talep formu',
  infoTitle: 'İletişim bilgileri',
  formTitle: 'İletişim formu',
  fields: {
    name: { n: '01', label: 'Ad Soyad', error: 'Lütfen adınızı ve soyadınızı yazın.' },
    email: { n: '02', label: 'E-posta', error: 'Geçerli bir e-posta adresi yazın.' },
    phone: { n: '03', label: 'Telefon (isteğe bağlı)' },
    subject: { n: '04', label: 'Konu (isteğe bağlı)' },
    message: { n: '05', label: 'Mesaj', error: 'Lütfen mesajınızı yazın.' },
  },
  consent: {
    label: 'Aydınlatma Metni’ni okudum.',
    linkText: 'Aydınlatma Metni',
    error: 'Devam etmek için Aydınlatma Metni’ni okuduğunuzu onaylayın.',
  },
  warningTag: 'Gizli bilgi göndermeyin',
  warning: 'Bu forma gizli bilgi veya belge yazmayın. Form üzerinden yapılan yazışma avukat–müvekkil ilişkisi kurmaz.',
  submit: 'Gönder',
  sending: 'Gönderiliyor…',
  status: {
    invalid: 'Formda düzeltilmesi gereken {n} alan var.',
    success: 'Mesajınız iletildi.',
    mailto: 'E-posta uygulamanız açıldı. Mesajı oradan göndermeniz gerekir.',
    error: 'Mesaj gönderilemedi. Lütfen doğrudan {email} adresine yazın.',
    pending: 'İletişim bilgileri henüz eklenmedi; form etkin değildir.',
  },
  honeypotLabel: 'Bu alanı boş bırakın',
};
