// Practice areas. Wording rules: neutral description of what an area covers; no service verbs aimed at clients,
// no assurances, no "uzman", no outcome claims. Whether these areas get their own URLs is a client / bar decision.
// TODO(client): confirm the eight areas before launch.
export default {
  detail: {
    docket: 'Çalışma alanı',
    summaryLabel: 'Alan özeti',
    topicsTitle: 'Bu alandaki konu başlıkları',
    approachTitle: 'Süreç',
    ctaTitle: 'İletişim',
    ctaText: 'İletişim bilgileri ve form ana sayfadaki iletişim bölümünde yer alır.',
    ctaButton: 'İletişim',
    prev: 'Önceki alan',
    next: 'Sonraki alan',
    navLabel: 'Çalışma alanları arasında gezinme',
    backHome: 'Ana sayfaya dön',
    allAreas: 'Tüm faaliyet alanları',
  },
  areas: [
    {
      id: 'criminal',
      title: 'Ceza Hukuku',
      oneLine: 'Soruşturma ve kovuşturma aşamalarına ilişkin ceza hukuku konuları.',
      lede: 'Ceza hukuku alanındaki faaliyetler, soruşturma ve kovuşturma süreçlerine ilişkin konuları kapsar. Ceza muhakemesi, Türk Ceza Kanunu ve ilgili mevzuat bu alanın temel çerçevesini oluşturur.',
      topics: [
        'Soruşturma aşamasında şüpheli hakları',
        'Kovuşturma ve duruşma süreçleri',
        'Tutuklama ve adli kontrol itirazları',
        'Mağdur ve katılan hakları',
        'Kanun yolları: istinaf ve temyiz',
        'Ekonomik nitelikli suçlara ilişkin dosyalar',
      ],
      approach: 'Süreç, eldeki belgelerin incelenmesiyle başlar. Ardından usul ve süre bakımından durum yazılı olarak özetlenir; izlenecek yol müvekkille görüşülerek belirlenir.',
    },
    {
      id: 'commercial',
      title: 'Ticaret ve Şirketler Hukuku',
      oneLine: 'Şirketlerin kuruluş, işleyiş ve sözleşme ilişkilerine dair konular.',
      lede: 'Bu alan, şirketlerin kuruluşundan sona ermesine kadar ticari ilişkilerin hukuki çerçevesini kapsar. Ortaklar arası sözleşmeler, şirket organlarının kararları ve ticari alacak uyuşmazlıkları Türk Ticaret Kanunu ve ilgili mevzuatın konusudur.',
      topics: [
        'Şirket kuruluşu ve ana sözleşme düzenlemeleri',
        'Ortaklık ve pay devri sözleşmeleri',
        'Genel kurul ve yönetim kurulu kararları',
        'Ticari sözleşmelerin hazırlanması ve incelenmesi',
        'Ticari alacak ve tazminat uyuşmazlıkları',
        'Kıymetli evrak (çek, poliçe, bono) ilişkileri',
      ],
      approach: 'Talep, ilgili sözleşme ve şirket belgeleriyle birlikte incelenir. Hukuki çerçeve ve usul seçenekleri yazılı bir notla aktarılır; karar müvekkile aittir.',
    },
    {
      id: 'employment',
      title: 'İş ve Sosyal Güvenlik Hukuku',
      oneLine: 'İş ilişkisinden doğan uyuşmazlıklar ile sosyal sigorta konuları.',
      lede: 'İş hukuku alanındaki faaliyetler, iş sözleşmelerinin kurulması, yürütülmesi ve sona ermesiyle ilgili konuları kapsar. İş Kanunu, sosyal sigortalar mevzuatı ve yargı içtihatları bu alanın çerçevesini oluşturur.',
      topics: [
        'İş sözleşmelerinin hazırlanması ve incelenmesi',
        'Fesih ve işe iade süreçleri',
        'İşçilik alacakları (kıdem, ihbar tazminatı, fazla mesai)',
        'Zorunlu arabuluculuk ve dava süreçleri',
        'İş kazası ve meslek hastalığı dosyaları',
        'Sosyal sigorta ve hizmet tespiti uyuşmazlıkları',
      ],
      approach: 'İş sözleşmesi, bordro ve yazışmalar birlikte incelenir; süre ve zamanaşımı bakımından durum yazılı olarak ortaya konur. Arabuluculuk ve dava seçenekleri müvekkille görüşülür.',
    },
    {
      id: 'realestate',
      title: 'Gayrimenkul ve İnşaat Hukuku',
      oneLine: 'Taşınmaz devri, kira, kat mülkiyeti ve inşaat sözleşmelerine ilişkin konular.',
      lede: 'Bu alan, taşınmazların edinilmesi, kullanılması ve devrine ilişkin hukuki ilişkileri kapsar. Tapu kayıtları, kira ve satış sözleşmeleri ile yapı işlerine dair sözleşmeler Medeni Kanun, Kat Mülkiyeti Kanunu ve ilgili mevzuatın konusudur.',
      topics: [
        'Tapu kayıtları ve taşınmaz devri işlemleri',
        'Kira sözleşmeleri, tahliye ve kira tespiti',
        'Kat mülkiyeti ve ortak yönetim uyuşmazlıkları',
        'Kentsel dönüşüm ve arsa payı karşılığı inşaat sözleşmeleri',
        'Yapı ve eser sözleşmelerinden doğan uyuşmazlıklar',
        'Ortaklığın giderilmesi ve tapu iptal-tescil davaları',
      ],
      approach: 'Taşınmaza ilişkin tapu, imar ve sözleşme belgeleri birlikte incelenir. Hak ve yükümlülükler yazılı bir özetle aktarılır; işlem veya dava yolu müvekkille görüşülerek belirlenir.',
    },
    {
      id: 'family',
      title: 'Aile ve Miras Hukuku',
      oneLine: 'Evlilik birliği, boşanma, velayet ve miras ilişkilerine dair konular.',
      lede: 'Aile ve miras hukuku alanı; evlilik birliğinin sona ermesi, çocuğun durumu, mal rejimi ve miras paylaşımı gibi kişisel nitelikli konuları kapsar. Çerçeveyi Medeni Kanun hükümleri oluşturur.',
      topics: [
        'Anlaşmalı ve çekişmeli boşanma davaları',
        'Velayet, kişisel ilişki ve nafaka',
        'Mal rejiminin tasfiyesi ve katkı payı alacağı',
        'Mirasçılık belgesi ve miras paylaşımı',
        'Vasiyetname ve miras sözleşmeleri',
        'Tenkis ve muris muvazaası davaları',
      ],
      approach: 'Hukuki durum, süreler ve belgeler ilk aşamada yazılı olarak özetlenir; uzlaşma yolu ile dava yolu birlikte ele alınır. Karar müvekkile aittir.',
    },
    {
      id: 'enforcement',
      title: 'İcra ve İflas Hukuku',
      oneLine: 'Takip, itiraz, haciz ve iflas süreçlerine ilişkin konular.',
      lede: 'İcra ve iflas hukuku alanı, para alacaklarının takibine ve bu takiplere karşı itiraz ve şikâyet yollarına ilişkin konuları kapsar. İlamlı ve ilamsız takipler, haciz işlemleri, konkordato ve iflas İcra ve İflas Kanunu’nun konusudur.',
      topics: [
        'İlamsız icra takipleri ve ödeme emrine itiraz',
        'İlamlı icra takipleri',
        'Haciz, satış ve sıra cetveli işlemleri',
        'İtirazın iptali ve menfi tespit davaları',
        'Konkordato ve iflas süreçleri',
        'Kambiyo senetlerine özgü takip yolları',
      ],
      approach: 'Takip dosyasındaki belgeler ve tebligat tarihleri incelenir; itiraz ve başvuru süreleri bu tarihlere göre belirlenir. İzlenecek yol müvekkille görüşülür.',
    },
    {
      id: 'ip',
      title: 'Fikri Mülkiyet ve Bilişim Hukuku',
      oneLine: 'Marka, patent, telif hakları ile kişisel verilerin korunması ve bilişim konuları.',
      lede: 'Bu alan, marka, tasarım, patent ve eser üzerindeki haklarla birlikte bilişim ve kişisel verilerin korunması konularını kapsar. Tescil, hak ihlali ve sözleşmesel düzenlemeler Sınai Mülkiyet Kanunu, Fikir ve Sanat Eserleri Kanunu ve 6698 sayılı Kanun kapsamındadır. Teknik konularda belgeler ve bilirkişi raporları belirleyicidir.',
      topics: [
        'Marka ve tasarım başvuruları ile itiraz süreçleri',
        'Marka ve telif hakkı ihlali uyuşmazlıkları',
        'Lisans ve devir sözleşmeleri',
        'Yazılım ve dijital içerik sözleşmeleri',
        'Kişisel verilerin korunması (KVKK) uyumu ve başvuruları',
        'İnternet içeriğine erişim ve içerik kaldırma başvuruları',
      ],
      approach: 'Hak sahipliğini gösteren belgeler ve varsa tescil kayıtları incelenir. Süreler ve başvuru şartları yazılı olarak aktarılır; izlenecek yol müvekkille görüşülür.',
    },
    {
      id: 'arbitration',
      title: 'Tahkim ve Uyuşmazlık Çözümü',
      oneLine: 'Tahkim, arabuluculuk ve müzakere yoluyla uyuşmazlık çözümüne ilişkin konular.',
      lede: 'Bu alan, mahkeme dışında yürütülen uyuşmazlık çözüm yollarını kapsar. Tahkim şartı içeren sözleşmeler, tahkim ve arabuluculuk süreçleri, müzakere ve uzlaşma metinleri ilgili tahkim kuralları ile Hukuk Uyuşmazlıklarında Arabuluculuk Kanunu’nun konusudur.',
      topics: [
        'Tahkim şartının ve tahkim anlaşmasının incelenmesi',
        'Tahkim başvuruları',
        'Tahkim yargılaması',
        'Hakem kararının icrası ve iptali süreçleri',
        'Arabuluculuk süreci ve anlaşma metinleri',
        'Müzakere ve uzlaşma sözleşmelerinin hazırlanması',
      ],
      approach: 'Uyuşmazlığa konu sözleşme ve yazışmalar incelenir; başvurulabilecek yollar ile süreleri yazılı olarak karşılaştırılır. Yol seçimi müvekkile aittir.',
    },
  ],
};
