// Practice areas (all five have their own page). Wording rules: neutral description of what an area covers; no service verbs aimed at clients,
// no assurances, no "uzman", no outcome claims. Whether these areas get their own URLs is a client / bar decision.
// TODO(client): areas confirmed by the client 2026-10-05.
export default {
  detail: {
    summaryLabel: 'Alan özeti',
    topicsTitle: 'Bu alanda ele aldığımız konular',
    approachTitle: 'Nasıl ilerleriz',
    ctaTitle: 'İletişim',
    ctaText: 'İletişim bilgileri ve form ana sayfadaki iletişim bölümünde yer alır.',
    ctaButton: 'İletişim',
    prev: 'Önceki alan',
    next: 'Sonraki alan',
    navLabel: 'Çalışma alanları arasında gezinme',
    backHome: 'Ana sayfaya dön',
    allAreas: 'Tüm faaliyet alanları',
  },
  areas: [
    {
      id: 'enforcement',
      title: 'İcra ve İflas Hukuku',
      oneLine: 'Takip, itiraz, haciz ve iflas süreçlerine ilişkin konular.',
      lede: 'İcra ve iflas hukuku alanı, para alacaklarının takibine ve bu takiplere karşı itiraz ve şikâyet yollarına ilişkin konuları kapsar. İlamlı ve ilamsız takipler, haciz işlemleri, konkordato ve iflas İcra ve İflas Kanunu’nun konusudur.',
      topics: [
        'İlamsız icra takipleri ve ödeme emrine itiraz',
        'İlamlı icra takipleri',
        'Haciz, satış ve sıra cetveli işlemleri',
        'İtirazın iptali ve menfi tespit davaları',
        'Konkordato ve iflas süreçleri',
        'Kambiyo senetlerine özgü takip yolları',
      ],
      approach: 'Takip dosyasındaki belgeler ve tebligat tarihleri incelenir; itiraz ve başvuru süreleri bu tarihlere göre belirlenir. İzlenecek yol müvekkille görüşülür.',
    },
    {
      id: 'maritime',
      title: 'Deniz Hukuku',
      oneLine: 'Deniz ticareti, gemi alacakları, taşıma ve deniz sigortasına ilişkin konular.',
      lede: 'Deniz hukuku alanı; gemilerin edinilmesi ve işletilmesi, deniz yoluyla eşya ve yolcu taşıması, deniz kazaları ve deniz sigortası gibi konuları kapsar. Çerçeveyi Türk Ticaret Kanunu’nun deniz ticaretine ilişkin hükümleri ile ilgili uluslararası sözleşmeler oluşturur.',
      topics: [
        'Deniz yoluyla eşya taşıma sözleşmeleri ve konşimento',
        'Çarter sözleşmeleri',
        'Gemi alacakları, ihtiyati haciz ve gemi haczi',
        'Gemi sicili, ipotek ve gemi alım-satım sözleşmeleri',
        'Deniz kazaları, çatma ve kurtarma',
        'Deniz sigortası ve taşıma kaynaklı tazminat uyuşmazlıkları',
      ],
      approach: 'Sözleşme, konşimento ve gemi belgeleri birlikte incelenir; zamanaşımı ve başvuru süreleri bakımından durum yazılı olarak ortaya konur. Dava veya başvuru yolu müvekkille görüşülür.',
    },
    {
      id: 'criminal',
      title: 'Ceza Hukuku',
      oneLine: 'Soruşturma ve kovuşturma aşamalarına ilişkin ceza hukuku konuları.',
      lede: 'Ceza hukuku alanındaki faaliyetler, soruşturma ve kovuşturma süreçlerine ilişkin konuları kapsar. Ceza muhakemesi, Türk Ceza Kanunu ve ilgili mevzuat bu alanın temel çerçevesini oluşturur.',
      topics: [
        'Soruşturma aşamasında şüpheli hakları',
        'Kovuşturma ve duruşma süreçleri',
        'Tutuklama ve adli kontrol itirazları',
        'Mağdur ve katılan hakları',
        'Kanun yolları: istinaf ve temyiz',
        'Ekonomik nitelikli suçlara ilişkin dosyalar',
      ],
      approach: 'Süreç, eldeki belgelerin incelenmesiyle başlar. Ardından usul ve süre bakımından durum yazılı olarak özetlenir; izlenecek yol müvekkille görüşülerek belirlenir.',
    },
    {
      id: 'commercial',
      title: 'Ticaret Hukuku',
      oneLine: 'Ticari sözleşmeler, ticari alacaklar ve kıymetli evrak ilişkilerine dair konular.',
      lede: 'Ticaret hukuku alanı, tacirler arasındaki ve ticari işletmeye ilişkin hukuki ilişkileri kapsar. Ticari sözleşmeler, ticari alacak ve tazminat uyuşmazlıkları ile kıymetli evrak ilişkileri Türk Ticaret Kanunu ve ilgili mevzuatın konusudur.',
      topics: [
        'Ticari sözleşmelerin hazırlanması ve incelenmesi',
        'Ticari alacak ve tazminat uyuşmazlıkları',
        'Kıymetli evrak (çek, poliçe, bono) ilişkileri',
        'Distribütörlük, bayilik ve acentelik sözleşmeleri',
        'Ticari defterler ve ticari işletme devri',
        'Haksız rekabet uyuşmazlıkları',
      ],
      approach: 'Talep, ilgili sözleşme ve ticari belgelerle birlikte incelenir. Hukuki çerçeve ve usul seçenekleri yazılı bir notla aktarılır; karar müvekkile aittir.',
    },
    {
      id: 'corporate',
      title: 'Şirketler Hukuku ve Danışmanlık',
      oneLine: 'Şirketlerin kuruluş, işleyiş ve ortaklık ilişkilerine dair danışmanlık konuları.',
      lede: 'Bu alan, şirketlerin kuruluşundan sona ermesine kadar kurumsal işleyişin hukuki çerçevesini kapsar. Ortaklar arası sözleşmeler, şirket organlarının kararları ve şirketlere sunulan hukuki danışmanlık Türk Ticaret Kanunu ve ilgili mevzuatın konusudur.',
      topics: [
        'Şirket kuruluşu ve ana sözleşme düzenlemeleri',
        'Ortaklık ve pay devri sözleşmeleri',
        'Genel kurul ve yönetim kurulu kararları',
        'Birleşme, bölünme ve tür değiştirme işlemleri',
        'Şirketlere yönelik sürekli hukuki danışmanlık',
        'Şirket içi uyum ve sözleşme süreçlerinin düzenlenmesi',
      ],
      approach: 'Talep, şirketin esas sözleşmesi ve ilgili belgeleriyle birlikte incelenir. Hukuki çerçeve ve seçenekler yazılı bir notla aktarılır; karar müvekkile aittir.',
    },
  ],
};
