// Practice areas. Wording rules: "faaliyet" / "ele alınır" / "yürütülür"; never "uzman", never outcome claims.
// TODO(client): confirm the eight areas before launch.
export default {
  index: {
    eyebrow: 'Çalışma Alanları',
    h1: 'Çalışma alanları',
    lede: 'Karaman Berat Avukatlık Ortaklığı, aşağıdaki alanlarda dava ve danışmanlık faaliyeti yürütür. Bu liste, faaliyet alanlarının bilgilendirme amaçlı dökümüdür; herhangi bir üstünlük veya ihtisas beyanı içermez.',
    note: '',
  },
  detail: {
    topicsTitle: 'Bu alanda ele aldığımız konular',
    approachTitle: 'Nasıl ilerleriz',
    ctaTitle: 'İletişim',
    ctaText: 'İletişim bilgileri ve iletişim formu için iletişim sayfasına bakabilirsiniz.',
    ctaButton: 'Randevu Talep Et',
    otherAreas: 'Diğer çalışma alanları',
    backToIndex: 'Tüm çalışma alanları',
    prev: 'Önceki alan',
    next: 'Sonraki alan',
    navLabel: 'Çalışma alanları arasında gezinme',
  },
  areas: [
    {
      id: 'criminal',
      title: 'Ceza Hukuku',
      oneLine: 'Soruşturma ve kovuşturma aşamalarında savunma ve müdafilik.',
      lede: 'Ceza hukuku alanındaki çalışmalarımız, soruşturma ve kovuşturma süreçlerinde şüpheli, sanık ve mağdur vekilliğini kapsar. Dosya, ilgili kanun maddeleri ve yargı kararları ışığında incelenir; süreç boyunca müvekkil, atılan adımlar ve usul takvimi hakkında yazılı ve sözlü olarak bilgilendirilir. Her aşamada gizlilik ve savunma hakkı esas alınır.',
      topics: [
        'Soruşturma aşamasında şüpheli müdafiliği',
        'Kovuşturma ve duruşma süreçleri',
        'Tutuklama ve adli kontrol itirazları',
        'Mağdur ve katılan vekilliği',
        'Kanun yolları: istinaf ve temyiz',
        'Ekonomik nitelikli suçlara ilişkin dosyalar',
      ],
      approach: 'Dosya önce eldeki belgelerle birlikte incelenir; usul ve süre bakımından durum yazılı olarak özetlenir. Savunma yaklaşımı müvekkille görüşülerek belirlenir. Duruşma ve işlemler sonrasında gelişmeler ayrıca bildirilir. Müvekkilin talepleri ve dosyanın gerektirdiği belgeler kayıt altında tutulur.',
    },
    {
      id: 'commercial',
      title: 'Ticaret ve Şirketler Hukuku',
      oneLine: 'Şirketlerin kuruluş, işleyiş ve sözleşme ilişkilerine dair hukuki çalışmalar.',
      lede: 'Bu alandaki çalışmalarımız, şirketlerin kuruluşundan sona ermesine kadar ticari ilişkilerin hukuki çerçevesini kapsar. Ortaklar arası sözleşmeler, şirket organlarının kararları ve ticari alacak uyuşmazlıkları, Türk Ticaret Kanunu ve ilgili mevzuat ışığında değerlendirilir; yazılı görüş ve dava vekilliği olarak yürütülür.',
      topics: [
        'Şirket kuruluşu ve ana sözleşme düzenlemeleri',
        'Ortaklık ve pay devri sözleşmeleri',
        'Genel kurul ve yönetim kurulu kararları',
        'Ticari sözleşmelerin hazırlanması ve incelenmesi',
        'Ticari alacak ve tazminat uyuşmazlıkları',
        'Kıymetli evrak (çek, poliçe, bono) ilişkileri',
      ],
      approach: 'Talep, ilgili sözleşme ve şirket belgeleriyle birlikte incelenir. Hukuki çerçeve ve olası usul seçenekleri yazılı bir notla aktarılır. Karar müvekkile aittir; seçilen yol doğrultusunda belgeler hazırlanır ve gelişmeler düzenli olarak bildirilir. Sözleşme metinlerinde tarafların yükümlülükleri açık ve denetlenebilir biçimde yazılır.',
    },
    {
      id: 'employment',
      title: 'İş ve Sosyal Güvenlik Hukuku',
      oneLine: 'İşçi ve işveren ilişkilerinden doğan uyuşmazlıklar ile sosyal sigorta konuları.',
      lede: 'İş hukuku alanındaki çalışmalarımız, iş sözleşmelerinin kurulması, yürütülmesi ve sona ermesiyle ilgili konuları kapsar. İşçi ve işveren tarafında; iş kanunu, sosyal sigortalar mevzuatı ve yargı içtihatları çerçevesinde görüş hazırlanır, arabuluculuk ve dava süreçlerinde temsil sağlanır. Her iki tarafın hak ve yükümlülükleri belgelere dayanılarak değerlendirilir.',
      topics: [
        'İş sözleşmelerinin hazırlanması ve incelenmesi',
        'Fesih ve işe iade süreçleri',
        'İşçilik alacakları (kıdem, ihbar tazminatı, fazla mesai)',
        'Zorunlu arabuluculuk ve dava süreçleri',
        'İş kazası ve meslek hastalığı dosyaları',
        'Sosyal sigorta ve hizmet tespiti uyuşmazlıkları',
      ],
      approach: 'İş sözleşmesi, bordro ve yazışmalar birlikte incelenir; süre ve zamanaşımı bakımından durum baştan ortaya konur. Arabuluculuk ve dava seçenekleri müvekkille görüşülür. Tutulan kayıtlar ve yapılan başvurular aşama aşama bildirilir.',
    },
    {
      id: 'realestate',
      title: 'Gayrimenkul ve İnşaat Hukuku',
      oneLine: 'Taşınmaz devri, kira, kat mülkiyeti ve inşaat sözleşmelerine ilişkin çalışmalar.',
      lede: 'Bu alandaki çalışmalarımız, taşınmazların edinilmesi, kullanılması ve devrine ilişkin hukuki ilişkileri kapsar. Tapu kayıtları, kira ve satış sözleşmeleri ile yapı işlerine dair sözleşmeler; Medeni Kanun, Kat Mülkiyeti Kanunu ve ilgili mevzuat kapsamında incelenir, uyuşmazlık hâlinde dava ve tahkim süreçlerinde temsil yürütülür.',
      topics: [
        'Tapu kayıtları ve taşınmaz devri işlemleri',
        'Kira sözleşmeleri, tahliye ve kira tespiti',
        'Kat mülkiyeti ve ortak yönetim uyuşmazlıkları',
        'Kentsel dönüşüm ve arsa payı karşılığı inşaat sözleşmeleri',
        'Yapı ve eser sözleşmelerinden doğan uyuşmazlıklar',
        'Ortaklığın giderilmesi ve tapu iptal-tescil davaları',
      ],
      approach: 'Taşınmaza ilişkin tapu, imar ve sözleşme belgeleri birlikte incelenir. Hak ve yükümlülükler yazılı bir özetle aktarılır; işlem veya dava yolu müvekkille görüşülerek belirlenir. Süreç boyunca yapılan işlemler ve belgeler kayıt altında tutulur. Yerinde inceleme gerektiğinde bu husus önceden bildirilir.',
    },
    {
      id: 'family',
      title: 'Aile ve Miras Hukuku',
      oneLine: 'Evlilik birliği, boşanma, velayet ve miras ilişkilerine dair çalışmalar.',
      lede: 'Aile ve miras hukuku çalışmalarımız; evlilik birliğinin sona ermesi, çocuğun durumu, mal rejimi ve miras paylaşımı gibi kişisel nitelikli konuları kapsar. Bu dosyalarda gizlilik ve ölçülülük esastır; Medeni Kanun hükümleri çerçevesinde hukuki durum yazılı olarak açıklanır ve süreç adım adım aktarılır.',
      topics: [
        'Anlaşmalı ve çekişmeli boşanma davaları',
        'Velayet, kişisel ilişki ve nafaka',
        'Mal rejiminin tasfiyesi ve katkı payı alacağı',
        'Mirasçılık belgesi ve miras paylaşımı',
        'Vasiyetname ve miras sözleşmeleri',
        'Tenkis ve muris muvazaası davaları',
      ],
      approach: 'Görüşmeler gizlilik esasıyla yürütülür. Aile ve miras dosyalarında hukuki durum, süreler ve belgeler ilk aşamada yazılı olarak özetlenir; uzlaşma yolu ile dava yolu birlikte değerlendirilir. Her adım müvekkilin bilgisi dahilinde atılır. Görüşme notları ve belgeler dosyada düzenli biçimde saklanır.',
    },
    {
      id: 'enforcement',
      title: 'İcra ve İflas Hukuku',
      oneLine: 'Alacağın takibi, itiraz, haciz ve iflas süreçlerine ilişkin çalışmalar.',
      lede: 'İcra ve iflas hukuku çalışmalarımız, para alacaklarının takibi ile borçlu tarafın itiraz ve şikâyet süreçlerini kapsar. İcra ve İflas Kanunu çerçevesinde ilamlı ve ilamsız takipler, haciz işlemleri, konkordato ve iflas konuları; süre ve usul kurallarına dikkat edilerek yürütülür. Alacaklı ve borçlu taraflara ilişkin dosyalar ele alınır.',
      topics: [
        'İlamsız icra takipleri ve ödeme emrine itiraz',
        'İlamlı icra takipleri',
        'Haciz, satış ve sıra cetveli işlemleri',
        'İtirazın iptali ve menfi tespit davaları',
        'Konkordato ve iflas süreçleri',
        'Kambiyo senetlerine özgü takip yolları',
      ],
      approach: 'Takip dosyasındaki belgeler ve tebligat tarihleri ilk olarak kontrol edilir; itiraz ve başvuru süreleri takvime işlenir. İzlenecek yol müvekkille görüşülür. Yapılan işlemler ve dosyadaki güncel durum yazılı olarak paylaşılır. Vekâletname ve yetki belgeleri eksiksiz biçimde dosyada tutulur.',
    },
    {
      id: 'ip',
      title: 'Fikri Mülkiyet ve Bilişim Hukuku',
      oneLine: 'Marka, patent, telif hakları ile kişisel verilerin korunması ve bilişim konuları.',
      lede: 'Bu alandaki çalışmalarımız, marka, tasarım, patent ve eser üzerindeki haklarla birlikte bilişim ve kişisel verilerin korunması konularını kapsar. Tescil, hak ihlali ve sözleşmesel düzenlemeler; Sınai Mülkiyet Kanunu, Fikir ve Sanat Eserleri Kanunu ve 6698 sayılı Kanun çerçevesinde değerlendirilir. Teknik konularda ilgili belgeler ve bilirkişi raporları esas alınır.',
      topics: [
        'Marka ve tasarım başvuruları ile itiraz süreçleri',
        'Marka ve telif hakkı ihlali uyuşmazlıkları',
        'Lisans ve devir sözleşmeleri',
        'Yazılım ve dijital içerik sözleşmeleri',
        'Kişisel verilerin korunması (KVKK) uyumu ve başvuruları',
        'İnternet içeriğine erişim ve içerik kaldırma başvuruları',
      ],
      approach: 'Hak sahipliğini gösteren belgeler ve varsa tescil kayıtları incelenir. Sınai mülkiyet konularında süreler ve başvuru şartları önceden yazılı olarak aktarılır. Seçilen yol doğrultusunda başvuru veya dava dosyası hazırlanır ve gelişmeler bildirilir. Kişisel veri konularında aydınlatma ve başvuru usulleri ayrıca açıklanır.',
    },
    {
      id: 'arbitration',
      title: 'Tahkim ve Uyuşmazlık Çözümü',
      oneLine: 'Tahkim, arabuluculuk ve müzakere yoluyla uyuşmazlıkların yürütülmesi.',
      lede: 'Bu alandaki çalışmalarımız, mahkeme dışında yürütülen uyuşmazlık yollarını kapsar. Tahkim şartı içeren sözleşmelerin incelenmesi, tahkim ve arabuluculuk süreçlerinde temsil, müzakere ve uzlaşma metinlerinin hazırlanması; ilgili tahkim kuralları ve Hukuk Uyuşmazlıklarında Arabuluculuk Kanunu çerçevesinde yürütülür.',
      topics: [
        'Tahkim şartının ve tahkim anlaşmasının incelenmesi',
        'Tahkim başvuruları',
        'Tahkim yargılamasında temsil',
        'Hakem kararının icrası ve iptali süreçleri',
        'Arabuluculuk sürecinde temsil ve anlaşma metinleri',
        'Müzakere ve uzlaşma sözleşmelerinin hazırlanması',
      ],
      approach: 'Uyuşmazlığa konu sözleşme ve yazışmalar incelenir; başvurulabilecek yollar ile süreleri yazılı olarak karşılaştırılır. Yol seçimi müvekkile aittir. Tahkim veya arabuluculuk sürecinde yapılan işlemler, belgeler ve bekleyen adımlar müvekkile düzenli olarak bildirilir. Gizlilik yükümlülükleri sözleşmeye göre gözetilir.',
    },
  ],
};
