// Practice areas (English mirror). TODO(client): confirm the eight areas before launch.
export default {
  index: {
    eyebrow: 'Practice Areas',
    h1: 'Practice areas',
    lede: 'Karaman Berat Avukatlık Ortaklığı carries out litigation and advisory work in the following areas. This list is an informational description of fields of activity, not a claim of specialisation.',
    note: '',
  },
  detail: {
    topicsTitle: 'Matters we deal with in this area',
    approachTitle: 'How we proceed',
    ctaTitle: 'Contact',
    ctaText: 'Contact details and the contact form are on the contact page.',
    ctaButton: 'Request an Appointment',
    otherAreas: 'Other practice areas',
    backToIndex: 'All practice areas',
    prev: 'Previous area',
    next: 'Next area',
    navLabel: 'Navigate between practice areas',
  },
  areas: [
    {
      id: 'criminal',
      title: 'Criminal Law',
      oneLine: 'Defence and counsel during investigation and prosecution.',
      lede: 'Our criminal law work covers representation of suspects, defendants and victims during investigation and prosecution. The file is reviewed in light of the relevant statutes and case law, and the client is kept informed of each step and of the procedural timetable, in writing and orally. Confidentiality and the right of defence guide every stage.',
      topics: [
        'Suspect counsel at the investigation stage',
        'Prosecution and hearings',
        'Objections to detention and judicial control',
        'Representation of victims and interveners',
        'Appeals (istinaf and temyiz)',
        'Files concerning economic offences',
      ],
      approach: 'The file is first reviewed with the available documents and its procedural position and time limits are summarised in writing. The defence approach is settled with the client. Developments after hearings and filings are reported separately, and requests and documents are kept on record.',
    },
    {
      id: 'commercial',
      title: 'Commercial and Corporate Law',
      oneLine: 'Legal work on company formation, operation and contracts.',
      lede: 'This area covers the legal framework of commercial relations from a company’s formation to its termination. Shareholder agreements, resolutions of company bodies and commercial receivable disputes are assessed under the Turkish Commercial Code and related legislation, through written opinions and litigation.',
      topics: [
        'Company formation and articles of association',
        'Shareholding and share transfer agreements',
        'General assembly and board resolutions',
        'Drafting and reviewing commercial contracts',
        'Commercial receivable and damages disputes',
        'Negotiable instruments (cheques, bills, notes)',
      ],
      approach: 'The request is reviewed with the relevant contracts and company records. The legal framework and procedural options are given in a written note. The decision is the client’s; documents follow the chosen route and progress is reported regularly, with obligations stated clearly in contract texts.',
    },
    {
      id: 'employment',
      title: 'Employment and Social Security Law',
      oneLine: 'Disputes between employees and employers, and social insurance matters.',
      lede: 'Our employment work covers the formation, performance and termination of employment contracts. For employees and employers alike, opinions are prepared under labour legislation, social security rules and case law, with representation in mediation and court. The rights and obligations of both sides are assessed on the basis of documents.',
      topics: [
        'Drafting and reviewing employment contracts',
        'Termination and reinstatement',
        'Employment receivables (severance, notice pay, overtime)',
        'Mandatory mediation and litigation',
        'Work accident and occupational disease files',
        'Social insurance and service determination disputes',
      ],
      approach: 'The contract, payroll and correspondence are reviewed together, and limitation and time-limit positions are set out at the start. Mediation and litigation options are discussed with the client, and filings are reported stage by stage.',
    },
    {
      id: 'realestate',
      title: 'Real Estate and Construction Law',
      oneLine: 'Property transfers, leases, condominium ownership and construction contracts.',
      lede: 'This area covers legal relations concerning the acquisition, use and transfer of real property. Title records, lease and sale agreements and construction contracts are reviewed under the Civil Code, the Condominium Ownership Law and related legislation, with representation in court and arbitration where a dispute arises.',
      topics: [
        'Title records and property transfers',
        'Leases, eviction and rent determination',
        'Condominium and shared management disputes',
        'Urban regeneration and land-share construction contracts',
        'Disputes arising from construction and works contracts',
        'Partition and title cancellation-registration claims',
      ],
      approach: 'Title, zoning and contract documents are reviewed together. Rights and obligations are conveyed in a written summary, and the transaction or litigation route is settled with the client. Steps and documents are kept on record; any need for an on-site inspection is stated in advance.',
    },
    {
      id: 'family',
      title: 'Family and Inheritance Law',
      oneLine: 'Marriage, divorce, custody and inheritance matters.',
      lede: 'Our family and inheritance work covers personal matters such as the end of a marriage, the position of children, the property regime and the division of an estate. Confidentiality and proportion guide these files; the legal position is explained in writing under the Civil Code and the process is set out step by step.',
      topics: [
        'Uncontested and contested divorce',
        'Custody, contact and maintenance',
        'Liquidation of the property regime and contribution claims',
        'Certificates of inheritance and estate division',
        'Wills and inheritance contracts',
        'Reduction and sham-transaction claims',
      ],
      approach: 'Meetings are held in confidence. The legal position, time limits and documents are summarised in writing at the outset; settlement and litigation are considered together. Each step is taken with the client’s knowledge, and notes and documents are kept orderly on file.',
    },
    {
      id: 'enforcement',
      title: 'Enforcement and Bankruptcy Law',
      oneLine: 'Debt collection, objections, seizure and bankruptcy proceedings.',
      lede: 'Our enforcement and bankruptcy work covers the collection of monetary claims and the debtor’s objection and complaint procedures. Enforcement with and without a judgment, seizure, composition and bankruptcy matters are handled under the Enforcement and Bankruptcy Law with attention to time limits and procedure. Files concerning creditors and debtors are handled.',
      topics: [
        'Enforcement without judgment and objection to payment orders',
        'Enforcement based on judgments',
        'Seizure, sale and ranking procedures',
        'Actions to annul objections and negative declaratory actions',
        'Composition and bankruptcy proceedings',
        'Enforcement routes specific to bills and notes',
      ],
      approach: 'Documents and service dates on the enforcement file are checked first; objection and filing deadlines are entered in the calendar. The route is discussed with the client, and actions taken and the current position are shared in writing. Powers of attorney are kept complete and notifications monitored.',
    },
    {
      id: 'ip',
      title: 'Intellectual Property and Technology Law',
      oneLine: 'Trade marks, patents, copyright, data protection and IT matters.',
      lede: 'This area covers rights in trade marks, designs, patents and works, together with information technology and personal data protection. Registration, infringement and contractual arrangements are assessed under the Industrial Property Law, the Law on Intellectual and Artistic Works and Law No. 6698, based on documents and expert reports where technical points arise.',
      topics: [
        'Trade mark and design applications and oppositions',
        'Trade mark and copyright infringement disputes',
        'Licence and assignment agreements',
        'Software and digital content contracts',
        'Personal data protection (KVKK) compliance and filings',
        'Access-blocking and content-removal requests',
      ],
      approach: 'Documents showing ownership, and registration records where they exist, are reviewed. Time limits and filing conditions for industrial property are stated in writing beforehand. Filings or claims are prepared for the chosen route and progress is reported; personal data procedures are explained separately.',
    },
    {
      id: 'arbitration',
      title: 'Arbitration and Dispute Resolution',
      oneLine: 'Arbitration, mediation and negotiated resolution of disputes.',
      lede: 'This area covers dispute routes outside the courts. We review contracts containing arbitration clauses, represent clients in arbitration and mediation, and prepare negotiation and settlement texts under the applicable arbitration rules and the Law on Mediation in Civil Disputes.',
      topics: [
        'Reviewing arbitration clauses and agreements',
        'Arbitration filings',
        'Representation in arbitral proceedings',
        'Enforcement and set-aside of awards',
        'Representation in mediation and settlement texts',
        'Drafting negotiation and settlement agreements',
      ],
      approach: 'The contract and correspondence at issue are reviewed and the available routes and their time limits are compared in writing. The choice of route is the client’s. Steps, documents and pending actions are reported regularly, and confidentiality duties are observed as the contract provides.',
    },
  ],
};
