// GENERATED by scripts/wire-images.mjs. Do not edit. Overrides images.generated.js on equal names.
export const images = {
  "about-stair": {
    "src": "/images/about-stair-720.webp",
    "srcSet": "/images/about-stair-480.webp 480w, /images/about-stair-720.webp 720w",
    "width": 720,
    "height": 960,
    "aspect": "720 / 960"
  },
  "about-stamp": {
    "src": "/images/about-stamp-720.webp",
    "srcSet": "/images/about-stamp-480.webp 480w, /images/about-stamp-720.webp 720w",
    "width": 720,
    "height": 480,
    "aspect": "720 / 480"
  },
  "band-corridor": {
    "src": "/images/band-corridor-1600.webp",
    "srcSet": "/images/band-corridor-1600.webp 1600w",
    "width": 1600,
    "height": 356,
    "aspect": "1600 / 356"
  },
  "band-corridor-m": {
    "src": "/images/band-corridor-m-800.webp",
    "srcSet": "/images/band-corridor-m-800.webp 800w",
    "width": 800,
    "height": 348,
    "aspect": "800 / 348"
  },
  "contact-stacks": {
    "src": "/images/contact-stacks-880.webp",
    "srcSet": "/images/contact-stacks-560.webp 560w, /images/contact-stacks-880.webp 880w",
    "width": 880,
    "height": 660,
    "aspect": "880 / 660"
  },
  "faq-typewriter": {
    "src": "/images/faq-typewriter-880.webp",
    "srcSet": "/images/faq-typewriter-560.webp 560w, /images/faq-typewriter-880.webp 880w",
    "width": 880,
    "height": 1100,
    "aspect": "880 / 1100"
  },
  "hero-justice": {
    "src": "/images/hero-justice-1440.webp",
    "srcSet": "/images/hero-justice-1008.webp 1008w, /images/hero-justice-1440.webp 1440w",
    "width": 1440,
    "height": 1800,
    "aspect": "1440 / 1800"
  },
  "hero-tower": {
    "src": "/images/hero-tower-1008.webp",
    "srcSet": "/images/hero-tower-640.webp 640w, /images/hero-tower-720.webp 720w, /images/hero-tower-1008.webp 1008w",
    "width": 1008,
    "height": 916,
    "aspect": "1008 / 916"
  },
  "practice-aile-ve-miras-hukuku": {
    "src": "/images/practice-aile-ve-miras-hukuku-1600.webp",
    "srcSet": "/images/practice-aile-ve-miras-hukuku-800.webp 800w, /images/practice-aile-ve-miras-hukuku-1600.webp 1600w",
    "width": 1600,
    "height": 700,
    "aspect": "1600 / 700"
  },
  "practice-archive": {
    "src": "/images/practice-archive-880.webp",
    "srcSet": "/images/practice-archive-560.webp 560w, /images/practice-archive-880.webp 880w",
    "width": 880,
    "height": 1100,
    "aspect": "880 / 1100"
  },
  "practice-books": {
    "src": "/images/practice-books-880.webp",
    "srcSet": "/images/practice-books-560.webp 560w, /images/practice-books-880.webp 880w",
    "width": 880,
    "height": 1100,
    "aspect": "880 / 1100"
  },
  "practice-ceza-hukuku": {
    "src": "/images/practice-ceza-hukuku-1600.webp",
    "srcSet": "/images/practice-ceza-hukuku-800.webp 800w, /images/practice-ceza-hukuku-1600.webp 1600w",
    "width": 1600,
    "height": 700,
    "aspect": "1600 / 700"
  },
  "practice-fikri-mulkiyet-ve-bilisim-hukuku": {
    "src": "/images/practice-fikri-mulkiyet-ve-bilisim-hukuku-1600.webp",
    "srcSet": "/images/practice-fikri-mulkiyet-ve-bilisim-hukuku-800.webp 800w, /images/practice-fikri-mulkiyet-ve-bilisim-hukuku-1600.webp 1600w",
    "width": 1600,
    "height": 700,
    "aspect": "1600 / 700"
  },
  "practice-gayrimenkul-ve-insaat-hukuku": {
    "src": "/images/practice-gayrimenkul-ve-insaat-hukuku-1600.webp",
    "srcSet": "/images/practice-gayrimenkul-ve-insaat-hukuku-800.webp 800w, /images/practice-gayrimenkul-ve-insaat-hukuku-1600.webp 1600w",
    "width": 1600,
    "height": 700,
    "aspect": "1600 / 700"
  },
  "practice-icra-ve-iflas-hukuku": {
    "src": "/images/practice-icra-ve-iflas-hukuku-1600.webp",
    "srcSet": "/images/practice-icra-ve-iflas-hukuku-800.webp 800w, /images/practice-icra-ve-iflas-hukuku-1600.webp 1600w",
    "width": 1600,
    "height": 700,
    "aspect": "1600 / 700"
  },
  "practice-is-ve-sosyal-guvenlik-hukuku": {
    "src": "/images/practice-is-ve-sosyal-guvenlik-hukuku-1600.webp",
    "srcSet": "/images/practice-is-ve-sosyal-guvenlik-hukuku-800.webp 800w, /images/practice-is-ve-sosyal-guvenlik-hukuku-1600.webp 1600w",
    "width": 1600,
    "height": 700,
    "aspect": "1600 / 700"
  },
  "practice-tahkim-ve-uyusmazlik-cozumu": {
    "src": "/images/practice-tahkim-ve-uyusmazlik-cozumu-1600.webp",
    "srcSet": "/images/practice-tahkim-ve-uyusmazlik-cozumu-800.webp 800w, /images/practice-tahkim-ve-uyusmazlik-cozumu-1600.webp 1600w",
    "width": 1600,
    "height": 700,
    "aspect": "1600 / 700"
  },
  "practice-ticaret-ve-sirketler-hukuku": {
    "src": "/images/practice-ticaret-ve-sirketler-hukuku-1600.webp",
    "srcSet": "/images/practice-ticaret-ve-sirketler-hukuku-800.webp 800w, /images/practice-ticaret-ve-sirketler-hukuku-1600.webp 1600w",
    "width": 1600,
    "height": 700,
    "aspect": "1600 / 700"
  },
  "process-documents": {
    "src": "/images/process-documents-880.webp",
    "srcSet": "/images/process-documents-560.webp 560w, /images/process-documents-880.webp 880w",
    "width": 880,
    "height": 1100,
    "aspect": "880 / 1100"
  },
  "process-stair": {
    "src": "/images/process-stair-880.webp",
    "srcSet": "/images/process-stair-560.webp 560w, /images/process-stair-880.webp 880w",
    "width": 880,
    "height": 1100,
    "aspect": "880 / 1100"
  }
};

export default images;
