// Builds the site photography: .claude/images/graded/*.webp -> public/images/<name>-<w>.webp
// plus src/content/images.generated.js (name -> { src, srcSet, width, height, aspect }).
// Crops to the planned aspect around a focal point, resizes to display size (<= 2x), keeps the grayscale grade.
// Run: npm run images
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(root, '.claude', 'images', 'graded');
const OUT = path.join(root, 'public', 'images');
const MANIFEST = path.join(root, 'src', 'content', 'images.generated.js');
const MAX_BYTES = 120 * 1024;

// [source prefix, out name, [aspectW, aspectH], widths, focal x%, focal y%, quality]
const TABLE = [
  ['02', 'hero-tower', [11, 10], [640, 720, 1008], 50, 35, 52],
  ['03', 'about-stair', [3, 4], [480, 720], 50, 45, 72],
  ['18', 'about-stamp', [3, 2], [480, 720], 50, 50, 72],
  ['07', 'practice-archive', [4, 5], [560, 880], 50, 50, 52],
  ['05', 'process-stair', [4, 5], [560, 880], 50, 45, 58],
  ['10', 'band-corridor', [1600, 356], [1600], 50, 55, 66],
  ['10', 'band-corridor-m', [800, 348], [800], 50, 55, 70],
  ['14', 'faq-typewriter', [4, 5], [560, 880], 65, 50, 72],
  ['08', 'contact-stacks', [4, 3], [560, 880], 50, 38, 62],
];

const kb = (n) => `${(n / 1024).toFixed(1)} KB`;

async function findSource(prefix) {
  const files = await fs.readdir(SRC);
  const f = files.find((n) => n.startsWith(`${prefix}-`) && n.endsWith('.webp'));
  if (!f) throw new Error(`No graded source starting with ${prefix}- in ${SRC}`);
  return path.join(SRC, f);
}

async function cropBox(file, [aw, ah], fx, fy) {
  const { width: W, height: H } = await sharp(file).metadata();
  const target = aw / ah;
  let cw = W;
  let ch = Math.round(W / target);
  if (ch > H) {
    ch = H;
    cw = Math.round(H * target);
  }
  const left = Math.min(W - cw, Math.max(0, Math.round((W * fx) / 100 - cw / 2)));
  const top = Math.min(H - ch, Math.max(0, Math.round((H * fy) / 100 - ch / 2)));
  return { left, top, width: cw, height: ch };
}

await fs.rm(OUT, { recursive: true, force: true });
await fs.mkdir(OUT, { recursive: true });

const manifest = {};
let total = 0;
let failed = false;

for (const [prefix, name, aspect, widths, fx, fy, quality] of TABLE) {
  const file = await findSource(prefix);
  const box = await cropBox(file, aspect, fx, fy);
  const entries = [];
  for (const w of widths) {
    const h = Math.round((w * aspect[1]) / aspect[0]);
    const outName = `${name}-${w}.webp`;
    const buf = await sharp(file)
      .extract(box)
      .resize(w, h, { fit: 'fill' })
      .grayscale()
      .webp({ quality, effort: 6 })
      .toBuffer();
    await fs.writeFile(path.join(OUT, outName), buf);
    total += buf.length;
    entries.push({ w, h, file: outName, bytes: buf.length });
    const over = buf.length > MAX_BYTES;
    if (over) failed = true;
    console.log(`${over ? 'FAIL' : 'ok  '} ${outName.padEnd(30)} ${String(w).padStart(4)}x${String(h).padEnd(4)} ${kb(buf.length)}`);
  }
  const big = entries[entries.length - 1];
  manifest[name] = {
    src: `/images/${big.file}`,
    srcSet: entries.map((e) => `/images/${e.file} ${e.w}w`).join(', '),
    width: big.w,
    height: big.h,
    aspect: `${big.w} / ${big.h}`,
  };
}

const banner = '// GENERATED by scripts/build-images.mjs (npm run images). Do not edit.\n';
await fs.writeFile(MANIFEST, `${banner}export const images = ${JSON.stringify(manifest, null, 2)};\n\nexport default images;\n`);
console.log(`\n${Object.keys(manifest).length} images, ${kb(total)} total -> public/images, src/content/images.generated.js`);
if (failed) {
  console.error(`At least one file exceeds ${kb(MAX_BYTES)}.`);
  process.exit(1);
}
