// Scans public/images for "<name>-<width>.webp" files, groups them by <name> and writes
// src/content/images.auto.js (name -> { src, srcSet, width, height, aspect }). Read-only for public/images.
// Run after new images land: node scripts/wire-images.mjs   (also wired into `npm run build` via prebuild)
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIR = path.join(root, 'public', 'images');
const OUT = path.join(root, 'src', 'content', 'images.auto.js');

const files = (await fs.readdir(DIR)).filter((f) => f.endsWith('.webp'));
const groups = new Map();
for (const f of files) {
  const m = f.match(/^(.+)-(\d+)\.webp$/);
  if (!m) continue;
  const [, name, w] = m;
  if (!groups.has(name)) groups.set(name, []);
  groups.get(name).push({ file: f, w: Number(w) });
}

const manifest = {};
for (const [name, list] of [...groups].sort(([a], [b]) => a.localeCompare(b))) {
  list.sort((a, b) => a.w - b.w);
  const dims = [];
  for (const it of list) {
    const meta = await sharp(path.join(DIR, it.file)).metadata();
    dims.push({ ...it, width: meta.width, height: meta.height });
  }
  const big = dims[dims.length - 1];
  manifest[name] = {
    src: `/images/${big.file}`,
    srcSet: dims.map((d) => `/images/${d.file} ${d.width}w`).join(', '),
    width: big.width,
    height: big.height,
    aspect: `${big.width} / ${big.height}`,
  };
}

const banner = '// GENERATED by scripts/wire-images.mjs. Do not edit. Overrides images.generated.js on equal names.\n';
await fs.writeFile(OUT, `${banner}export const images = ${JSON.stringify(manifest, null, 2)};\n\nexport default images;\n`);
console.log(`wire-images: ${Object.keys(manifest).length} image groups -> src/content/images.auto.js`);
